"""powerpoint-review / review_deck_from_renders — shots manifest → review deck.

Parameter resolution: stdin JSON (dcc-mcp-core execute_script) or CLI flags.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from dcc_mcp_powerpoint.compiler import compile_deck
from dcc_mcp_powerpoint.deck_ir import (
    DeckEnvelope,
    Metadata,
    PresentationIr,
    Slide,
    artifact_stem,
)
from dcc_mcp_powerpoint.render import render_deck
from dcc_mcp_powerpoint.validate import validate_artifacts


def _force_utf8_stdio() -> None:
    """Deterministic output contract: stdout/stderr are always UTF-8."""
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8", errors="replace")


def _load_manifest(path: str | Path) -> dict:
    manifest_path = Path(path)
    if not manifest_path.is_file():
        raise FileNotFoundError(f"manifest not found: {manifest_path}")
    return json.loads(manifest_path.read_text(encoding="utf-8"))


def build_envelope(manifest: dict) -> DeckEnvelope:
    """Shots manifest → Deck IR envelope (contract, never raw coordinates)."""
    shots = manifest.get("shots", [])
    if not shots:
        raise ValueError("manifest has no shots")
    title = str(manifest.get("title", "Production Review"))
    document_id = str(manifest.get("document_id", "draft:review-deck"))

    slides: list[Slide] = [
        Slide(
            semantic_layout="title_cover",
            title=title,
            content_blocks=({"type": "text", "paragraphs": [f"{len(shots)} shots · generated by dcc-mcp-PowerPoint"]},),
            speaker_notes="Review deck generated from DCC render pipeline.",
        ),
        Slide(
            semantic_layout="bullets",
            title="Shot / Asset 清单",
            content_blocks=({"type": "bullets", "items": [f"{s.get('name', '?')} — {s.get('version', '?')} ({s.get('artist', '?')})" for s in shots]},),
        ),
    ]

    missing = 0
    for shot in shots:
        image = str(shot.get("image", ""))
        has_image = bool(image) and Path(image).is_file()
        if not has_image:
            missing += 1
        blocks = [
            {"type": "image", "resource": image} if has_image else {"type": "bullets", "items": ["missing_asset: 渲染产物缺失"]},
            {
                "type": "bullets",
                "items": [
                    f"名称: {shot.get('name', '?')}",
                    f"版本: {shot.get('version', '?')}",
                    f"制作: {shot.get('artist', '?')}",
                    f"日期: {shot.get('date', '?')}",
                    f"备注: {shot.get('notes', '—')}",
                ],
            },
        ]
        slides.append(Slide(semantic_layout="image_left_text_right", title=str(shot.get("name", "Shot")), content_blocks=tuple(blocks)))

    slides.append(
        Slide(
            semantic_layout="closing",
            title="Thanks",
            content_blocks=({"type": "text", "paragraphs": [f"覆盖 {len(shots)} 个 shot/asset，缺失资产 {missing} 个"]},),
        )
    )

    return DeckEnvelope(
        schema_version="office-ir/1.0",
        kind="presentation",
        document_id=document_id,
        metadata=Metadata(title=title, author="DCC-MCP Agent", language="zh-CN"),
        document=PresentationIr(slides=tuple(slides)),
        outputs=("pptx", "pdf", "slide-previews"),
    )


def run(params: dict) -> None:
    envelope = build_envelope(_load_manifest(params["input"]))
    out_dir = Path(params.get("output_dir", "output"))
    pptx = compile_deck(envelope, out_dir / f"{artifact_stem(envelope.document_id)}.pptx")
    artifacts = [str(pptx)]
    if params.get("render", True):
        report = render_deck(pptx, out_dir)
        if report.get("pdf"):
            artifacts.append(report["pdf"])
        if report.get("previews"):
            artifacts.extend(report["previews"])
    artifact_report = validate_artifacts(artifacts)
    print(
        json.dumps(
            {
                "success": artifact_report["ok"],
                "message": f"review deck '{envelope.document_id}' ({len(envelope.document.slides)} slides)",
                "context": {"artifacts": artifacts, "artifacts_ok": artifact_report, "source_manifest": params["input"]},
            },
            ensure_ascii=False,
        )
    )


def main() -> None:
    _force_utf8_stdio()
    params: dict = {}
    if not sys.stdin.isatty():
        raw = sys.stdin.read()
        if raw.strip():
            try:
                params = json.loads(raw)
            except json.JSONDecodeError:
                params = {}
    if not params:
        parser = argparse.ArgumentParser(description="Shots manifest → review deck")
        parser.add_argument("--input", required=True)
        parser.add_argument("--out", dest="output_dir", default="output")
        parser.add_argument("--render", dest="render", action=argparse.BooleanOptionalAction, default=True)
        params = vars(parser.parse_args())
    try:
        run(params)
    except Exception as exc:  # noqa: BLE001
        print(json.dumps({"success": False, "message": str(exc), "context": {}}, ensure_ascii=False))
        sys.exit(1)


if __name__ == "__main__":
    main()
