"""Smart layer system for PPTX decks — semantic shape layers.

A layer is a semantic group of shapes. Membership is recorded in the shape
name as a native OOXML tag (cNvPr/@name):

    "<base name> ::layer=<layer>"

Native tagging means layers survive PowerPoint and python-pptx round-trips
with no sidecar files. Layer operations (visibility, z-order, recolor) edit
the slide spTree XML directly, so they work on decks generated by the Deck
compiler and on decks produced anywhere else.

Default layers emitted by the Deck compiler (see compiler.py):

    background  full-slide background rects
    decoration  ghost circles, logos, hairline separators
    header      slide titles, section numbers, cover titles, column headers
    content     bullets, panels, cards, pictures, captions
    accent      accent rules, chips, timeline line/numbers, connectors
    footer      deck-title footer, page numbers

This module is opt-in (never imported at package import time): it uses
python-pptx, a dev/test-only dependency, same policy as compiler/analyze.
"""

from __future__ import annotations

import re
from typing import Any

from pptx.dml.color import RGBColor
from pptx.enum.dml import MSO_FILL
from pptx.enum.shapes import MSO_SHAPE_TYPE
from pptx.oxml.ns import qn

LAYER_TAG = "::layer="
LAYER_NAME_RE = re.compile(r"^[A-Za-z][A-Za-z0-9_-]{0,31}$")

# Layers the Deck compiler guarantees on generated decks (documentation +
# validation aid; any valid layer name works at runtime).
BUILTIN_LAYERS = ("background", "decoration", "header", "content", "accent", "footer")


def split_layer_name(name: str) -> tuple[str, str | None]:
    """Split a shape name into (base_name, layer). Layer is None when untagged."""
    marker = name.rfind(LAYER_TAG)
    if marker == -1:
        return name, None
    return name[:marker].strip(), name[marker + len(LAYER_TAG) :].strip()


def shape_layer(shape) -> str | None:
    """Layer tag of a python-pptx shape, or None."""
    return split_layer_name(shape.name)[1]


def tag_shape(shape, layer: str) -> str:
    """Tag a shape into a layer and return its new name.

    Idempotent: an existing tag is replaced, not stacked.
    """
    _require_layer(layer)
    base, _ = split_layer_name(shape.name)
    name = f"{base} {LAYER_TAG}{layer}".strip()
    shape.name = name
    return name


def _require_layer(layer: str) -> None:
    if not isinstance(layer, str) or not LAYER_NAME_RE.match(layer):
        raise ValueError(f"invalid layer name {layer!r} (expected {LAYER_NAME_RE.pattern})")


def _c_nv_pr(element) -> Any:
    """cNvPr element of any shape element (sp/pic/graphicFrame/cxnSp/grpSp)."""
    holder = element.find(qn("p:nvGrpSpPr"))
    if holder is not None:
        return holder.find(qn("p:cNvPr"))
    for prefix in ("nvSpPr", "nvPicPr", "nvGraphicFramePr", "nvCxnSpPr"):
        holder = element.find(qn(f"p:{prefix}"))
        if holder is not None:
            return holder.find(qn("p:cNvPr"))
    return None


def _shape_id(shape) -> str:
    c_nv_pr = _c_nv_pr(shape._element)
    return c_nv_pr.get("id", "") if c_nv_pr is not None else ""


def _shape_type(shape) -> str:
    kind = shape.shape_type
    if kind in (MSO_SHAPE_TYPE.PICTURE, MSO_SHAPE_TYPE.LINKED_PICTURE):
        return "picture"
    if kind == MSO_SHAPE_TYPE.LINE:
        return "connector"
    if kind == MSO_SHAPE_TYPE.GROUP:
        return "group"
    if kind == MSO_SHAPE_TYPE.TABLE:
        return "table"
    if kind == MSO_SHAPE_TYPE.CHART:
        return "chart"
    if kind == MSO_SHAPE_TYPE.TEXT_BOX:
        return "textbox"
    if kind == MSO_SHAPE_TYPE.AUTO_SHAPE:
        has_text = getattr(shape, "has_text_frame", False) and bool(shape.text_frame.text.strip())
        return "textbox" if has_text else "shape"
    return "shape"


def _text_preview(shape, limit: int = 50) -> str:
    if not getattr(shape, "has_text_frame", False):
        return ""
    text = shape.text_frame.text.strip().replace("\n", " / ")
    return text[:limit] + ("…" if len(text) > limit else "")


def _is_hidden(shape) -> bool:
    return shape._element.get("hidden") == "1"


def _member_shapes(prs, layer: str, slides: list[int] | None = None) -> list[tuple[int, Any]]:
    """(slide_index, shape) pairs for every shape tagged with the layer.

    slide_index is 1-based; ``slides`` is a 1-based filter (None = all).
    """
    targets = set(slides) if slides else None
    found: list[tuple[int, Any]] = []
    for index, slide in enumerate(prs.slides, start=1):
        if targets is not None and index not in targets:
            continue
        for shape in slide.shapes:
            if shape_layer(shape) == layer:
                found.append((index, shape))
    return found


def list_layers(prs, path: str = "") -> dict[str, Any]:
    """Layer inventory across every slide (JSON-able report)."""
    layers: dict[str, dict[str, Any]] = {}
    untagged: list[dict[str, Any]] = []
    for index, slide in enumerate(prs.slides, start=1):
        for position, shape in enumerate(slide.shapes, start=1):
            layer = shape_layer(shape)
            if layer is None:
                untagged.append(
                    {"slide": index, "index": position, "name": shape.name or "", "type": _shape_type(shape)}
                )
                continue
            entry = layers.setdefault(layer, {"name": layer, "total": 0, "slides": {}})
            key = str(index)
            per_slide = entry["slides"].get(key)
            if per_slide is None:
                per_slide = {"slide": index, "count": 0, "visible": True, "z": [], "shapes": []}
                entry["slides"][key] = per_slide
            entry["total"] += 1
            per_slide["count"] += 1
            per_slide["z"].append(position)
            if _is_hidden(shape):
                per_slide["visible"] = False
            per_slide["shapes"].append(
                {
                    "name": shape.name,
                    "id": _shape_id(shape),
                    "type": _shape_type(shape),
                    "text": _text_preview(shape),
                    "hidden": _is_hidden(shape),
                }
            )
    report = [
        {
            "name": entry["name"],
            "total": entry["total"],
            "slides": [
                {
                    "slide": per_slide["slide"],
                    "count": per_slide["count"],
                    "visible": per_slide["visible"],
                    "z": f"{min(per_slide['z'])}..{max(per_slide['z'])}",
                    "shapes": per_slide["shapes"],
                }
                for per_slide in entry["slides"].values()
            ],
        }
        for entry in layers.values()
    ]
    return {
        "path": path,
        "slide_count": len(prs.slides._sldIdLst),
        "layers": report,
        "untagged": untagged,
    }


def set_layer_visibility(prs, layer: str, visible: bool, slides: list[int] | None = None) -> dict[str, Any]:
    """Show/hide every shape in a layer via the native sp hidden attribute."""
    _require_layer(layer)
    changed = 0
    per_slide: dict[int, int] = {}
    for index, shape in _member_shapes(prs, layer, slides):
        element = shape._element
        if visible:
            if element.get("hidden") is not None:
                del element.attrib["hidden"]
                changed += 1
                per_slide[index] = per_slide.get(index, 0) + 1
        elif element.get("hidden") != "1":
            element.set("hidden", "1")
            changed += 1
            per_slide[index] = per_slide.get(index, 0) + 1
    return {"layer": layer, "visible": visible, "changed": changed, "per_slide": per_slide}


def _parse_position(position: str) -> tuple[str, str | None]:
    if position in ("front", "back"):
        return position, None
    for prefix in ("above ", "below "):
        if position.startswith(prefix):
            reference = position[len(prefix) :].strip()
            if LAYER_NAME_RE.match(reference):
                return prefix.strip(), reference
    raise ValueError("position must be 'front', 'back', 'above <layer>' or 'below <layer>'")


def reorder_layer(prs, layer: str, position: str, slides: list[int] | None = None) -> dict[str, Any]:
    """Move a layer in the z-order of every slide (or the selected slides).

    z-order semantics: later children of p:spTree render on top, so 'front'
    re-appends the layer's shapes after all other shapes; 'back' re-inserts
    them right after the spTree header; 'above/below <layer>' aligns against
    the first/last shape of a reference layer on each slide.
    """
    _require_layer(layer)
    action, reference = _parse_position(position)
    moved = 0
    skipped: list[int] = []
    for index, slide in enumerate(prs.slides, start=1):
        if slides is not None and index not in slides:
            continue
        sp_tree = slide.shapes._spTree
        members = [shape._element for shape in slide.shapes if shape_layer(shape) == layer]
        if not members:
            continue
        for element in members:
            sp_tree.remove(element)
        if action == "front":
            insert = len(sp_tree) - (1 if sp_tree[-1].tag == qn("p:extLst") else 0)
        elif action == "back":
            insert = 2  # after nvGrpSpPr + grpSpPr
        else:
            reference_elements = [shape._element for shape in slide.shapes if shape_layer(shape) == reference]
            if not reference_elements:
                insert = 2
                skipped.append(index)
            elif action == "above":
                insert = sp_tree.index(reference_elements[-1]) + 1
            else:
                insert = sp_tree.index(reference_elements[0])
        for offset, element in enumerate(members):
            sp_tree.insert(insert + offset, element)
        moved += 1
    return {
        "layer": layer,
        "position": position,
        "slides_moved": moved,
        "slides_skipped": skipped,
    }


def _hex_color(value: str) -> RGBColor:
    hex_value = value.strip().lstrip("#")
    if len(hex_value) != 6 or not re.fullmatch(r"[0-9A-Fa-f]{6}", hex_value):
        raise ValueError(f"invalid hex color {value!r} (expected RRGGBB)")
    return RGBColor(int(hex_value[0:2], 16), int(hex_value[2:4], 16), int(hex_value[4:6], 16))


def recolor_layer(
    prs,
    layer: str,
    *,
    fill: str | None = None,
    line: str | None = None,
    text: str | None = None,
    slides: list[int] | None = None,
) -> dict[str, Any]:
    """Restyle every shape in a layer: solid fill / solid line / run color.

    Only explicitly-set (solid) fills and lines are touched; inherited or
    theme colors are skipped and reported, never guessed.
    """
    _require_layer(layer)
    if fill is None and line is None and text is None:
        raise ValueError("recolor_layer needs at least one of fill, line, text")
    fill_rgb = _hex_color(fill) if fill else None
    line_rgb = _hex_color(line) if line else None
    text_rgb = _hex_color(text) if text else None
    details: dict[str, int] = {"fill": 0, "line": 0, "text_runs": 0}
    for _index, shape in _member_shapes(prs, layer, slides):
        if fill_rgb is not None:
            try:
                if shape.fill.type == MSO_FILL.SOLID:
                    shape.fill.fore_color.rgb = fill_rgb
                    details["fill"] += 1
            except (AttributeError, TypeError):
                pass
        if line_rgb is not None:
            try:
                if shape.line.fill.type == MSO_FILL.SOLID:
                    shape.line.color.rgb = line_rgb
                    details["line"] += 1
            except (AttributeError, TypeError):
                pass
        if text_rgb is not None and getattr(shape, "has_text_frame", False):
            for paragraph in shape.text_frame.paragraphs:
                for run in paragraph.runs:
                    run.font.color.rgb = text_rgb
                    details["text_runs"] += 1
    return {"layer": layer, "applied": details["fill"] + details["line"] + details["text_runs"], "details": details, "fill": fill, "line": line, "text": text}


def assign_layer(
    prs,
    layer: str,
    *,
    slides: list[int] | None = None,
    shape: str | None = None,
    shape_id: str | int | None = None,
    all_shapes: bool = False,
) -> dict[str, Any]:
    """Tag existing shapes into a layer by selector.

    Selectors combine with AND; at least one of shape/shape_id/all_shapes
    must be given. ``shape`` matches the shape name exactly or as a
    substring.
    """
    _require_layer(layer)
    if not (shape or shape_id is not None or all_shapes):
        raise ValueError("assign_layer needs at least one selector: shape, shape_id or all_shapes")
    target_id = str(shape_id) if shape_id is not None else None
    tagged: list[dict[str, Any]] = []
    for index, slide in enumerate(prs.slides, start=1):
        if slides is not None and index not in slides:
            continue
        for candidate in slide.shapes:
            matched = False
            if all_shapes:
                matched = True
            if shape is not None and (shape == candidate.name or shape in candidate.name):
                matched = True
            if target_id is not None and _shape_id(candidate) == target_id:
                matched = True
            if matched:
                tagged.append(
                    {
                        "slide": index,
                        "name": tag_shape(candidate, layer),
                        "id": _shape_id(candidate),
                        "type": _shape_type(candidate),
                    }
                )
    if not tagged:
        raise ValueError("no shapes matched the selector")
    return {"layer": layer, "tagged": len(tagged), "shapes": tagged}


def shape_tree(prs, path: str = "", slide: int | None = None) -> dict[str, Any]:
    """Per-slide shape tree with addressing info (index/name/id/layer/type)."""
    slides_out: list[dict[str, Any]] = []
    for index, sl in enumerate(prs.slides, start=1):
        if slide is not None and index != slide:
            continue
        shapes = []
        for position, shape in enumerate(sl.shapes, start=1):
            shapes.append(
                {
                    "index": position,
                    "name": shape.name or "",
                    "id": _shape_id(shape),
                    "layer": shape_layer(shape),
                    "type": _shape_type(shape),
                    "text": _text_preview(shape),
                    "hidden": _is_hidden(shape),
                }
            )
        slides_out.append({"slide": index, "shapes": shapes})
    return {"path": path, "slide_count": len(prs.slides._sldIdLst), "slides": slides_out}
